Repository CCI-MOC/hil, pull requests merged in 2018-05, with the labels that each got.

#1000 Refactor dellnos9 and brocade switch drivers
  hil/ext/switches/_vlan_http.py
  hil/ext/switches/brocade.py
  hil/ext/switches/dellnos9.py
  tests/unit/ext/switches/brocade.py
Labels: waiting on +2, waiting on reviewer

#1011 Make running pycodestyle slightly more ergonomic.
  ci/pycodestyle_tests.sh
Labels: easy, waiting on submitter

#1002 Implement the first couple obmd-related api calls.
  .travis.yml
  ci/obmd/install.sh
  ci/obmd/run_integration_tests.sh
  docs/rest_api.md
  hil/api.py
  hil/cli/node.py
  hil/client/node.py
  hil/model.py
  tests/integration/obmd.py
  tests/unit/client.py
Labels: waiting on +2, waiting on reviewer

#1008 Make travis a little faster
  .coveragerc
  .travis.yml
  README.rst
  ci/apache/install.sh
  ci/apache/run_integration_tests.sh
  ci/deployment-mock-networks/run_integration_tests.sh
  ci/hil_install.sh
  ci/keystone/install.sh
  ci/keystone/run_integration_tests.sh
  ci/obmd/run_integration_tests.sh
  ci/run_tests.sh
  ci/run_unit_tests.sh
  setup.py
  tests/integration/client.py
Labels: waiting on +2, waiting on reviewer

#1010 Fix a bug that was silencing errors from the server.
  hil/client/base.py
  hil/test_common.py
  tests/integration/client.py
  tests/unit/client.py
Labels: waiting on submitter

#1013 Optimize postgres to make it run slightly faster
  .travis.yml
  ci/optimize_postgres.sh
Labels: enhancement, waiting on submitter

#1007 Redirect obm api calls to obmd
  .travis.yml
  ci/apache/hil.cfg.postgres
  ci/obmd/install.sh
  ci/obmd/run_integration_tests.sh
  hil/api.py
  hil/cli/node.py
  hil/test_common.py
  tests/integration/cli.py
  tests/integration/client.py
  tests/integration/obmd.py
  tests/unit/api/auth.py
  tests/unit/api/main.py
  tests/unit/ext/obm/ipmi.py
Labels: waiting on +2, waiting on reviewer
