Repository CCI-MOC/hil, pull requests merged in 2018-02, with the labels that each got.

#939 API for node_register
  hil/cli.py
  hil/client/node.py
  hil/errors.py
  tests/unit/client.py
Labels: waiting on reviewer

#953 obmd data migration script
  .travis.yml
  ci/obmd/run_integration_tests.sh
  hil/commands/admin.py
  hil/commands/migrate_ipmi_info.py
  tests/integration/migrate_ipmi_info.py
Labels: waiting on reviewer

#951 DOCS MATTER!
  AUTHORS
  docs/INSTALL.rst
  docs/USING.rst
  docs/client-library.md
Labels: cleanup, documentation, waiting on +2, waiting on reviewer

#934 List public networks as a regular user
  docs/rest_api.md
  hil/api.py
  tests/unit/api/main.py
Labels: waiting on +2, waiting on reviewer

#945 Add list_users (admin operation)
  docs/rest_api.md
  hil/cli.py
  hil/client/user.py
  hil/ext/auth/database.py
  tests/unit/client.py
  tests/unit/ext/auth/database.py
Labels: waiting on reviewer

#959 Document the initial port state
  docs/deployment.md
  docs/network-drivers.md
Labels: documentation, waiting on +2, waiting on reviewer

#961 Remove pytest-catchlog from dependences.
  setup.py
  tests/unit/rest.py
Labels: waiting on +2, waiting on reviewer

#954 Add list_network_attachments to the client library
  hil/cli.py
  hil/client/network.py
  tests/unit/client.py
Labels: waiting on +2, waiting on reviewer

#955 Add unimplemented client library functions
  hil/cli.py
  hil/client/node.py
  tests/unit/client.py
Labels: waiting on +2, waiting on reviewer

#936 Openvpn spec
  specs/openvpn-support.md
Labels: waiting on +2, waiting on reviewer

#957 Add code coverage with coveralls.io
  .coveragerc
  .gitignore
  .travis.yml
  README.rst
  ci/apache/run_integration_tests.sh
  ci/deployment-mock-networks/run_integration_tests.sh
  ci/keystone/run_integration_tests.sh
  ci/obmd/run_integration_tests.sh
  ci/run_unit_tests.sh
  setup.py
Labels: enhancement, ready to merge, waiting on reviewer
