Repository CCI-MOC/hil, pull requests merged in 2018-04, with the labels that each got.

#969 CLI using Click
  ci/apache/run_integration_tests.sh
  docs/INSTALL-devel-tldr.rst
  docs/INSTALL-devel.rst
  docs/INSTALL.rst
  docs/USING.rst
  examples/dbinit.py
  examples/hil.cfg
  hil/cli.py
  hil/cli/__init__.py
  hil/cli/cli.py
  hil/cli/client_setup.py
  hil/cli/headnode.py
  hil/cli/misc.py
  hil/cli/network.py
  hil/cli/node.py
  hil/cli/port.py
  hil/cli/project.py
  hil/cli/switch.py
  hil/cli/user.py
  hil/commands/admin.py
  scripts/hil
  scripts/hil-complete.sh
  scripts/hil_network.service
  setup.py
  tests/integration/cli.py
  tests/integration/keystone.py
  tests/unit/cli.py
Labels: discuss, high priority, waiting on reviewer

#987 Add release notes section to UPGRADING document.
  docs/UPGRADING.rst
Labels: do not merge yet

#988 API should be versioned
  docs/USING.rst
  docs/rest_api.md
  hil/client/base.py
  hil/client/project.py
  hil/client/switch.py
  hil/client/user.py
  hil/rest.py
  tests/integration/keystone.py
  tests/stress.py
  tests/unit/client.py
  tests/unit/hil_auth.py
  tests/unit/rest.py
Labels: waiting on reviewer

#989 Test fixes
  hil/test_common.py
  setup.py
  tests/unit/dev_support.py
Labels: waiting on reviewer

#990 Fix lax schema for node_register api call.
  hil/api.py
  hil/rest.py
  tests/unit/api/main.py
Labels: waiting on reviewer

#897 Openvswitch driver
  docs/network-drivers.md
  hil/cli/switch.py
  hil/ext/switches/common.py
  hil/ext/switches/ovs.py
Labels: waiting on reviewer
