Repository CCI-MOC/hil, pull requests merged in 2018-03, with the labels that each got.

#967 Bug Fix: Omit coverage test in virtualenv
  .coveragerc
Labels: bug, high priority, waiting on reviewer

#965 _assert_absent and friends are having better names now
  hil/api.py
  hil/ext/auth/database.py
  tests/deployment/native_networks.py
  tests/deployment/vlan_networks.py
  tests/unit/api/main.py
  tests/unit/api/maintenance-pool.py
  tests/unit/ext/auth/database.py
  tests/unit/ext/network_allocators/vlan_pool.py
  tests/unit/ext/switches/dellnos9.py
Labels: easy, naming, waiting on +2, waiting on reviewer

#963 Update Switch Drivers to Handle Errors
  hil/ext/switches/brocade.py
Labels: discuss, waiting on +2, waiting on reviewer

#958 Require setting a native vlan before adding any trunk vlans on the brocade switch (and correctly parse range of vlans)
  hil/ext/switches/brocade.py
  hil/ext/switches/common.py
  hil/ext/switches/dellnos9.py
  tests/unit/ext/switches/brocade.py
  tests/unit/ext/switches/common.py
Labels: waiting on reviewer

#974 Fix the broken link on Alembic
  docs/migrations.md
Labels: documentation, easy

#971 Enforce unique contraints on object names/labels in the database.
  hil/migrations/versions/264ddaebdfcc_make_labels_unique.py
  hil/migrations/versions/89ff8a6d72b2_add_uuid_and_status_to_networkingaction.py
  hil/model.py
  tests/unit/deferred.py
Labels: WIP, easy

#972 Move show_console to the client library
  hil/cli.py
  hil/client/node.py
  hil/ext/obm/mock.py
  tests/unit/client.py
Labels: easy, waiting on reviewer

#977 Upgrade Flask from 0.10.1 -> 0.11.1 -> 0.12.1
  setup.py
Labels: discuss

#982 Use flask_script since flask.ext.script is deprecated (in admin.py)
  hil/commands/admin.py
Labels: easy, waiting on reviewer
